# WARNING 
# For Local Development/Testing Purposes Only
version: '3'

services:
  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile